### ISSUE TITLE
Add possibility to start as a different user?

### ISSUE THREAD

**Issue by miekg** [miekg/dinit#10]
Note sure if this would be worthwhile, but it might make sense to start a process under a different user.
This could be a flag `-user` which would start all processes as that user. Or there could be an alternate starting syntax:
```
-u USER CMD OPT1 OPT2 ... OPTN
````

**Comment by qiukeren** [comment]
in my mind it should rely on the programme's script, such as redis, mysql.

**Comment by miekg** [comment]
I.e. don't do it in dinit?

**Comment by qiukeren** [comment]
Sorry sir, redis's user and group does not rely on the init script but on the init program, 

Do it is good^

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [dinit] Add possibility to star..." ]
>Sorry sir, redis's user and group does not rely on the init script but on the init program,
>
>Do it is good^

OK :-)

/Miek

--
Miek Gieben

**Comment by miekg** [comment]
Think it is easier (if you need this functionality) to work around it by using a startup script where you sudo to the currect user and then exec the stuff you need. No actual need to do this in dinit - which I like to keep simple.

**Comment by miekg** [comment]
Inclined to close, unless you're providing a real elegant way of doing this in the form of a PR :)

Closing for now.
