### ISSUE TITLE
-r does not support PATH?

### ISSUE THREAD

**Issue by rjma** [miekg/dinit#13]
Hi,
Thanks for this great tool. 

It seems -r does not support PATH environment variable. Every time I have to specify the full path explicitly, which is not so convenient especially for executing 'docker exec'.
Interestingly, it seems the DINIT_START does support PATH.

**Comment by miekg** [comment]
Feel free to fix by sending a PR. Wondering why DINIT_START does seem to work with the PATH, as both get (in the end) run with cmd.Start()
