### ISSUE TITLE
can I start dinit with no run commands

### ISSUE THREAD

**Issue by paulczar** [miekg/dinit#7]
I have a start script `/app/bin/boot` that sets up a bunch of stuff and starts a few processes backgrounded.   I would love to set `ENTRYPOINT dinit -start /app/bin/boot -primary`

and then be able to call `dinit -submit -r confd -node $ETCD -config-file /app/confd.toml` from inside my boot script to actually start the processes I want `dinit` to manage.

However `dinit` appears to require at least one process be specified when starting it.

**Comment by miekg** [comment]
Basically you sort of proposing a daemon mode for dinit; stay around for command(s) to be submitted. Sounds like something that should be possible.

**Comment by paulczar** [comment]
yeah that. :)

**Comment by miekg** [comment]
Care to submit a PR? I prolly won't have time for this any time soon...

You can also use a sleep script to do what you want: have `dinit` start a script with `while true; do sleep 1; done` in it (which might actually be a nice work around)

**Comment by miekg** [comment]
I can probably live with the `while-true-sleep-1` work-around.

**Comment by miekg** [comment]
work around should be good enough. Closing
